#!/bin/bash -e
wget --no-verbose https://flatassembler.net/fasmg.zip --output-document=/tmp/fasmg.zip
case "$TRAVIS_OS_NAME" in
    linux)  unzip /tmp/fasmg.zip fasmg ;;
    osx)    wget --no-verbose https://board.flatassembler.net/files/fasmg_macosx_132.zip --output-document=/tmp/fasmg_macosx.zip
	    unzip -d fasmg /tmp/fasmg.zip
	    unzip -d fasmg /tmp/fasmg_macosx.zip
	    patch --batch --directory=fasmg --unified --input=macosx.patch --strip=0
	    fasmg/fasmg fasmg/source/libc/fasmg.asm fasmg/fasmg.elf
	    objconv -fmacho32 -nu fasmg/fasmg.{elf,macho}
	    `which gcc clang | head --lines=1` -m32 -Wl,-no_pie fasmg/fasmg.macho -o fasmg ;;
    *)      echo "Unknown OS: $TRAVIS_OS_NAME" >2
	    exit 1
esac
chmod +x fasmg
