#!/bin/bash
passed=0
failed=0
total=0
for test in "$(dirname "$0")"/*.asm; do
	test="${test%.asm}"
	if fasmg -v 1 -e 9999 "$test.asm" "$test.out" && diff "$test.out" "$test.bin" >/dev/null; then
		echo -e "\e[32m$test passed.\e[m"
		((passed++))
	else
		echo -e "\e[31m$test failed.\e[m"
		((failed++))
	fi
done
echo -e "===\e[32m $passed tests passed \e[31m $failed tests failed \e[m==="
((failed == 0))
